version: '3'

services:
  postgres_java:
    image: postgres
    container_name: postgres_java
    ports:
      - "5432:5432"
    restart: "no"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "123456789"

  api:
    build:
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres_java/postgres
      DATABASE_USER: postgres_user
      DATABASE_PASSWORD: 123456789
